version: '3'

services:
  apache:
    build: apache
    ports:
      - 8082:80
    networks:
      - docker_net 

  mysql:
    build: mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=docker_test
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - docker_net 

networks:
  docker_net:

volumes:
  db-data:

